### ISSUE TITLE
resetSelectedValues() does not immediately clear the selected values

### ISSUE THREAD

**Issue by solankirohan** [srigar/multiselect-react-dropdown#62]
I have added a Reset button on the UI which would reset the selected values of the dropdown. I am using resetSelectedValues() function to reset the dropdown values, this method works fine i.e. it updates the dropdown immediately but what I am observing is when I print the selected items using this.testRef.current.getSelectedItems() method just after the resetSelectedValues() call, it still returns the previously selected items, expected is that it should return no values.

**Comment by srigar** [comment]
Because we calling setState on `resetSelectedValues` and where setState is a async, so it was not working. Now I changed the `resetSelectedValues` function as a promise, so use `await` keyword it will work as expected. changes available in **`v1.6.1`**

`      await this.ref.current.resetSelectedValues();
        console.log('get', this.ref.current.getSelectedItems());
`
